name: Deploy para AWS Lambda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Configurar credenciais AWS
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Criar e ativar virtualenv
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install zappa

    - name: Gerar zappa_settings.json
      run: |
        echo '{
          "production": {
            "app_function": "app.app",
            "aws_region": "sa-east-1",
            "project_name": "de-lambda-api",
            "runtime": "python3.9",
            "s3_bucket": "zappa-deploys-nicholasyukio",
            "environment_variables": {
              "ASAAS_API_KEY": "$ASAAS_API_KEY"
            }
          }
        }' > zappa_settings.json

    - name: Deploy com Zappa
      env:
        ASAAS_API_KEY: ${{ secrets.ASAAS_API_KEY }}
      run: |
        source venv/bin/activate
        zappa update productionE